#!/bin/bash

# ALWAYS when updating or messing with this make sure that
# 1. Filename and SONAME match in the library under PLATFORM/lib
# 2. The zlib.pc refers to the right file

set -e



DIR=$(readlink -f $(dirname $0))


${WDY_XBUILD_ROOT}/bin/cmake-android-build ${DIR} 
	
${WDY_XBUILD_ROOT}/bin/prepare_libraries.sh


